import React from 'react'

function Settings() {
  return (
    <div>
        <p className='pt-5'>

          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam, voluptatibus tempore sit consequuntur ut ratione totam, nihil reiciendis numquam voluptates debitis rem quidem. Accusantium ex excepturi provident nisi suscipit iste?
          Incidunt nulla suscipit aspernatur facere nisi corporis doloribus, repellat, consectetur atque sunt illum culpa dignissimos corrupti debitis quasi recusandae esse quas aliquid. Commodi amet, rerum quidem ducimus cum alias eaque?
          Laborum illum quasi sint enim aliquam. Ipsum sint repellendus aliquam? Eos facilis tempora provident eveniet et aliquid incidunt. Quos reprehenderit expedita vel voluptas veniam quibusdam impedit sit pariatur facilis soluta.
          Unde aut voluptas illum, eaque incidunt enim esse. Ut beatae mollitia fuga cupiditate quae? Placeat consequuntur quaerat ducimus laboriosam architecto optio molestiae, voluptatibus dignissimos saepe perspiciatis, similique commodi explicabo necessitatibus?
          Ratione quos iusto cum nisi eius! Accusamus fugiat placeat consequatur architecto sequi aspernatur similique aliquam. Esse sapiente quaerat fugiat vel consequatur. Veritatis id at asperiores modi nostrum? Quam, quas corporis.
          Voluptate molestias officia quis iure iusto, quidem saepe ipsam eos, assumenda, voluptatibus quibusdam doloribus veniam soluta asperiores natus. Ipsam reiciendis repellat praesentium cumque eius iusto voluptatibus debitis aliquam vero modi!
          Sed tempore, sunt quisquam blanditiis pariatur nulla non facere commodi praesentium delectus unde ullam libero. Quos magni nam reiciendis reprehenderit officiis quod id, officia consequuntur at, est voluptatibus aspernatur ab.
          Aperiam porro libero corrupti quidem obcaecati maxime vitae mollitia illo. Doloribus, porro quidem! Minima dolorum cum tempore iusto, animi eaque, velit dolor porro earum officia qui beatae quidem nulla quas?
          Est, blanditiis reprehenderit quam voluptatibus praesentium animi eius veritatis deserunt autem culpa, accusantium delectus nam. Ipsa, cum sunt sit aliquid officia temporibus sapiente reprehenderit illo velit est? Amet, aliquam veritatis.
          Facilis consequuntur mollitia ut, sint, error velit ipsa praesentium beatae illo non atque tempora repellat recusandae optio odit labore tenetur? Commodi laudantium, error doloremque sapiente esse possimus eligendi sunt temporibus.
          Laborum, ex? Ab obcaecati suscipit iste debitis, numquam consectetur tempore at rerum omnis totam blanditiis, nostrum nulla porro itaque ratione impedit! Facere numquam sequi neque nesciunt odio repellat, ipsum in!
          Eaque porro, accusantium, aliquam doloribus rerum at consectetur ipsum repellat fugiat, dignissimos et optio voluptatem provident voluptate! Quos quidem tempore, maiores necessitatibus fugiat in explicabo animi fugit laboriosam, quam temporibus.
          Eos totam eius repellat quaerat labore voluptatum vel numquam, quod fugiat error deserunt ad, saepe libero. Omnis totam itaque voluptas quidem iure similique, expedita beatae nisi maxime placeat sed deleniti?
          Rem voluptas voluptatibus impedit nisi eius excepturi nesciunt, ex delectus atque vero ducimus totam dolores eos explicabo quo neque porro ipsam maiores, pariatur natus hic nulla corrupti dolorem nemo. Ducimus?
          Impedit beatae reprehenderit, odio fugiat itaque ab omnis earum sequi, adipisci tempora sed soluta debitis temporibus, ad saepe libero voluptatem asperiores atque similique sapiente. Quia consequatur commodi reiciendis dolore laborum?
          Quo dicta quibusdam aperiam. Odit praesentium illo quidem. Nostrum id ea rerum in illum cum esse natus ratione, ipsam illo obcaecati voluptate! Itaque amet pariatur quam est animi harum facere!
          Quas quod eum voluptatibus nulla fuga optio. Iste maxime, beatae consequatur et dolor rem doloribus perferendis enim voluptatibus sapiente. Voluptatibus explicabo laborum labore temporibus id voluptates, reprehenderit odit quo laboriosam!
          Et maiores saepe cum ipsum assumenda vero quisquam cupiditate dolor delectus quos beatae quas suscipit quis harum porro, distinctio atque error rem alias at voluptate iusto animi perferendis quidem! Impedit!
          Aliquam, sapiente veritatis! In provident nam, est natus aliquam sed mollitia laudantium iste consequatur voluptate, facilis animi illo perspiciatis eaque eius quibusdam, asperiores ducimus suscipit doloribus atque nulla voluptatum nihil.
          Ab odit perspiciatis necessitatibus incidunt, asperiores tempora fuga! Magni libero minus ipsa dolores iure dolor laboriosam cum excepturi accusantium laborum officia vero quasi, sed minima est dignissimos quam, voluptatem assumenda!
          Officia aperiam commodi maxime mollitia dignissimos error soluta ad nemo explicabo vero perspiciatis blanditiis velit fuga libero deleniti, pariatur quis doloribus ipsam ex architecto eos et dolore. Nostrum, nihil enim.
          Quas, corporis ipsam quos, nam quidem accusantium officia, accusamus expedita vel placeat libero alias eaque quae natus unde earum tenetur cumque explicabo. Aperiam consequuntur voluptates possimus? Pariatur quam consequatur alias.
          Impedit nihil non dolorum obcaecati, dolores nulla maxime neque laboriosam quisquam animi ipsam, sapiente, facilis quas? Dolore voluptatibus itaque in libero, dicta, sed, eligendi impedit animi nisi voluptas tempora accusantium.
          Laudantium, maxime quibusdam? Perferendis sapiente, magnam temporibus eos aliquid impedit cumque neque provident, iure harum porro tempora adipisci velit suscipit ipsum aperiam autem qui id commodi. Nulla laborum dignissimos maiores.
          Officiis nobis voluptates debitis, quaerat beatae delectus dolorum obcaecati dicta vel incidunt iusto, aliquid facilis hic sint quidem earum sapiente vitae ea veritatis rem porro ad nesciunt aut. Ea, neque!
          Repellat ipsam iste praesentium voluptate libero. In magnam doloremque velit illum eligendi, atque vero, voluptas quod tenetur aspernatur dolores alias exercitationem? Necessitatibus laboriosam iusto facilis iste nemo accusantium officia nobis.
          Nisi eveniet ex facilis sint ad? Harum est et id rem, aspernatur, doloribus numquam odit expedita fugit libero reprehenderit amet eum dolore molestias, facere at labore officiis iure accusantium mollitia.
          Incidunt nihil soluta reprehenderit eligendi accusantium blanditiis fugit dignissimos doloribus voluptatum fuga consequatur, odit provident neque, voluptatem molestiae tempora! Quos totam officiis omnis placeat sit esse id repellendus, numquam accusantium!
          Excepturi tempora amet debitis ipsam dolores est tempore et iste, deleniti alias veniam ea inventore magnam doloribus esse? Veritatis harum nihil maiores laboriosam animi nemo fugiat ipsam alias ex laborum?
          Exercitationem ullam dicta debitis nihil. Ratione, sit! Non earum nesciunt maxime accusantium vero hic, harum adipisci voluptatibus nostrum sapiente officia molestiae nobis perferendis id quas est laborum aspernatur. Quia, distinctio!
          Nam dolorem aperiam consequuntur eligendi! Dolore ut soluta recusandae nemo repellendus quisquam nobis ipsam! In veniam molestiae sed voluptates autem dolorum repudiandae consequuntur, soluta voluptas. Temporibus voluptates necessitatibus est unde!
          Soluta voluptates vero tempora tempore rem omnis numquam cupiditate officia incidunt corrupti? Excepturi, voluptas odit inventore distinctio illo saepe, ut fuga deserunt voluptatum delectus doloribus quia sapiente beatae nulla earum!
          Libero nihil dicta rerum consequatur minima culpa voluptates soluta sit nam quasi, dolore sequi hic. Quod minus vero repellat molestias rem nam, suscipit praesentium nulla voluptatibus unde repudiandae consectetur similique!
          Commodi consequatur neque porro repudiandae quia id fugit provident mollitia ipsam cumque delectus ad soluta, dolor ex impedit. Consequatur, asperiores eaque! Voluptatum modi beatae numquam sunt velit, voluptates sed voluptate.
          Voluptatibus, possimus. Ipsam harum, enim incidunt atque quod necessitatibus fugit vel, quaerat doloribus exercitationem nostrum? Ab est, amet quasi maiores iusto, ipsum possimus commodi aspernatur sed adipisci dolor dolorum nesciunt.
          Veritatis neque modi impedit repudiandae, odit natus ipsam, ipsa dolores accusamus saepe cum dicta consequatur, voluptas obcaecati beatae? Ab tempora repudiandae dolor reprehenderit officia quae! Veritatis rerum labore accusantium facilis.
          Odit a mollitia hic ullam libero nulla, voluptatem exercitationem deserunt rem. Voluptate dignissimos perferendis sunt quo facere est iure quod omnis exercitationem fugit. Iure reiciendis fugit aut facere asperiores ut?
          Quia voluptatum rerum harum, nostrum illo voluptatem doloremque alias illum iusto provident amet vel inventore molestiae, nobis non voluptas neque sunt! Neque, commodi! Maiores maxime molestias iure suscipit quasi impedit.
          Voluptate aperiam, vel quis sit repudiandae ut totam delectus at modi quas repellendus cum, aliquid voluptates dolorum rem cumque quia? Ipsam voluptas enim placeat facilis modi quasi vero obcaecati totam!
          Nisi atque corrupti nesciunt quam labore blanditiis sapiente ad explicabo porro cum accusamus, soluta cupiditate impedit, fugit necessitatibus minus deleniti itaque ullam. Labore et iure corporis dolor reprehenderit ad eius.
          Commodi, aspernatur reiciendis. Consectetur, ut amet numquam, nemo aliquam dolorum hic ipsa quibusdam unde quos ducimus minus nam nostrum asperiores commodi, accusamus fugiat officia sed aliquid obcaecati soluta! Quod, natus!
          Quisquam sunt est alias iusto pariatur ducimus voluptas quidem minus assumenda vel, quo distinctio ullam ea aliquam molestiae tenetur quos non perferendis vero id eaque. Veniam nam excepturi placeat obcaecati.
          Ducimus, dolores aliquid. Blanditiis vel quibusdam deleniti nihil reiciendis odio rem, exercitationem, laboriosam ullam eveniet repudiandae? Consequatur exercitationem molestiae ducimus doloremque, saepe nemo soluta qui ex fugit magnam iure itaque?
          Nihil eos perferendis nobis deleniti totam praesentium sapiente recusandae doloremque vitae porro. Maxime libero eveniet, sequi in aliquid architecto deserunt magnam mollitia molestias possimus, soluta autem quibusdam aspernatur alias saepe!
          Perferendis, aliquam totam saepe officiis explicabo reiciendis, atque voluptas sit nostrum quisquam, minima fugit enim alias maxime ea? Laudantium non laboriosam repudiandae eaque deleniti optio pariatur ipsum neque iusto vitae!
          Blanditiis repellat nesciunt enim pariatur magnam quidem eligendi architecto consectetur id? Vero inventore repellendus recusandae laboriosam accusamus atque. Architecto corrupti quis possimus ipsam! Asperiores ad qui eum magni voluptatum vero.
          Tempora odio impedit minus labore! Ducimus rerum unde soluta porro sunt repellat, voluptates ea nam dolorem odio numquam consectetur enim consequatur cumque reprehenderit amet facilis culpa dolores mollitia? Ipsa, consequuntur.
          Sint temporibus quam vero sapiente aliquam in facilis hic, quisquam voluptate incidunt eaque ducimus deserunt nam corporis ab ut. Dolores dolor asperiores libero quis beatae nihil aliquid vero alias autem!
          Facere, fugit deleniti magnam neque dolores quo non nesciunt officiis reprehenderit a quam fugiat maxime sit recusandae nihil obcaecati ratione impedit consequatur dolorum autem ut! Dolorum aliquam magni nostrum eum.
          Laboriosam magnam animi magni necessitatibus obcaecati ad dicta, saepe, eius ea debitis rem ipsa amet dolorem aspernatur dolore voluptatum id excepturi velit quos! Modi, tempora dolore. Hic incidunt eum unde.
          Mollitia ab optio dolorem provident voluptate incidunt delectus ipsum reprehenderit, est similique iusto minus omnis obcaecati, nostrum excepturi consequuntur facere a. Ea maiores alias, aliquid modi ad cupiditate nesciunt iure?
          Quos repellat, repudiandae exercitationem vel ad expedita magni qui eligendi in placeat nobis itaque deleniti aut pariatur aperiam blanditiis maiores autem dolore voluptates architecto voluptate suscipit assumenda accusantium! Optio, commodi.
          Numquam quae cupiditate accusantium dolorum. Incidunt corrupti ullam molestias inventore iure perferendis id itaque quis maiores non unde porro dolores officia vero odio, nesciunt dolor tenetur, labore, possimus doloribus expedita!
          Sequi unde natus ullam magni quis earum quasi similique placeat cum ad autem necessitatibus modi maiores iste, assumenda est fuga blanditiis, quia excepturi illo molestias quaerat vero adipisci saepe. Ipsam.
          Facilis sequi accusantium non! Accusamus illo officia cum vero, esse molestiae explicabo ea natus repellendus deserunt laborum accusantium. Soluta blanditiis provident est perspiciatis magni modi, aperiam maiores explicabo? Velit, eaque.
          Laborum repudiandae nostrum adipisci fugit veritatis dolorum modi numquam sunt ipsa id neque quasi porro laboriosam architecto consequuntur quos iste impedit deserunt incidunt voluptatibus sequi, itaque reiciendis. Maiores, nobis eius!
          Animi cupiditate quos doloribus ea totam aliquid eius reprehenderit hic accusamus aperiam nostrum saepe exercitationem similique, at perspiciatis dignissimos incidunt. Necessitatibus suscipit praesentium cupiditate quisquam numquam rerum corporis debitis architecto!
          Id consequatur vero iste quasi laboriosam dolor voluptas, possimus eius, excepturi voluptate expedita magni officia doloremque non ut accusamus earum ipsum quo aspernatur facere tempore odio. Doloribus repellat aliquid commodi.
          Enim quidem, labore minus, illum ipsum error illo veritatis at excepturi est vitae maxime amet maiores ratione consectetur voluptatem sapiente eveniet aspernatur explicabo impedit delectus rem. Suscipit consequuntur possimus illo.
          Harum, iusto! Quis eum quo in iure similique molestiae nam magni illo quidem libero dolore, ipsum fugit aliquam architecto ducimus eius ipsam incidunt eveniet! Nihil culpa quae voluptatem vero asperiores.
          Eos atque dolores nam officia quidem, exercitationem vero illum dolore ipsum et fugiat itaque ea laboriosam molestiae eum maiores doloribus perspiciatis voluptatibus? Deserunt, omnis quidem magni distinctio sit maxime eveniet!
          Ratione, odio non? Veniam assumenda quam quas nobis culpa inventore quis ad, accusamus, quia ex aliquid laudantium explicabo iusto harum cum doloremque necessitatibus expedita. Quisquam labore autem aliquam obcaecati porro.
          Sunt et qui quam est rerum tempore voluptatum nostrum magnam. Ipsum veritatis sint laboriosam eaque corporis natus magnam, nemo consectetur harum accusamus adipisci soluta sit recusandae dolorem est voluptatum inventore.
          Temporibus iusto eveniet nisi velit fugit amet nobis consectetur? Quod quos enim officiis, dolores blanditiis debitis, porro nesciunt sunt ratione quibusdam minima labore, voluptatem vero magnam maiores atque voluptate assumenda.
          Nulla quasi, perferendis, modi veniam debitis iusto soluta, tenetur harum molestiae fuga voluptatem voluptate nostrum distinctio incidunt molestias amet tempora dolorum omnis cupiditate architecto fugiat minima? Voluptas dolorum fuga inventore.
          Ea doloribus nostrum voluptate eos, cumque repellendus quas aut rem quaerat omnis fugiat distinctio veritatis tempora quibusdam, blanditiis libero accusamus. Obcaecati dolores reiciendis aliquam eius dignissimos veritatis id ullam tempore.
          Repudiandae, accusamus quisquam. Consectetur exercitationem vitae recusandae iure numquam quasi voluptatem atque dolorem rerum hic explicabo maiores odio sed architecto, accusamus blanditiis cupiditate saepe soluta non aliquid veritatis in corporis!
          Nisi, molestias a accusantium eveniet itaque commodi natus doloremque ab impedit maxime cupiditate? Nostrum dicta obcaecati asperiores quidem, repudiandae ad cupiditate. Officia provident facere laborum expedita molestias reiciendis voluptate veniam!
          Alias quo possimus aliquam id animi maxime vero, reprehenderit, quidem dolor provident distinctio ducimus in exercitationem, expedita facilis saepe. Nulla eveniet nobis voluptatum et. Beatae autem iste a quisquam repellat.
          Illum similique totam magni? Ea, recusandae laborum fugit quam iure dolores consectetur accusantium? Ratione, dolorum veritatis, similique reiciendis accusantium explicabo molestias ab ad ipsam voluptates aperiam deserunt eum atque nam?
          Doloremque possimus expedita soluta architecto pariatur dolores rem voluptas, dolorem placeat, dolorum qui minima tempore obcaecati iusto harum consequuntur neque! Inventore optio soluta repudiandae nemo est autem laudantium non dolorem?
          Aliquam officiis inventore reiciendis corrupti laborum ullam? Sequi veniam iusto cupiditate. Iure minima eum aut voluptate praesentium deleniti, earum ipsum ratione in consequatur, atque consequuntur ipsa aliquam dolor tempore accusamus?
          Culpa provident veniam corporis vitae. Sapiente cumque animi, quo tempora alias doloremque reiciendis dolores harum nobis beatae, molestias corrupti optio eos repellendus ab, voluptates accusamus at asperiores veritatis mollitia deleniti!
          Maxime molestias impedit consectetur sint saepe eos ratione distinctio exercitationem reprehenderit rem iste quo fugit perferendis tempore enim, beatae cum suscipit hic iure nam commodi doloremque eveniet obcaecati sit. Illo!
          Saepe accusantium voluptate ullam excepturi blanditiis quas, consequatur dolore, alias placeat eaque exercitationem aliquam perspiciatis. Minus quibusdam necessitatibus, consectetur incidunt, iure, saepe et excepturi suscipit id magni molestiae reiciendis quaerat?
          Iure ea quod consequuntur dolore voluptatem. Sit libero architecto perspiciatis sunt facere consequuntur eius quod nobis quasi dolorum ducimus quis provident explicabo, illum veniam tempore. Culpa quam dolore maiores quae!
          Explicabo omnis est voluptatem rem saepe laborum ullam recusandae debitis! Ex, inventore amet dicta molestias nam rem architecto suscipit facere, mollitia quae magnam. Quo eius blanditiis doloremque. Vero, accusantium obcaecati.
          Fugit, perspiciatis? Dolorem, quaerat reprehenderit, totam eveniet explicabo quasi laborum consequatur quo minima consequuntur corporis labore aliquam? Beatae ullam nam explicabo exercitationem aut illum, ipsum asperiores quaerat, maiores ea est?
          Beatae ea magnam illo minus sint commodi aliquam voluptatibus? Modi, ad molestias ratione dicta deleniti accusamus eius nemo quibusdam vel eaque porro asperiores corrupti illum, debitis dolorum. Quia, perspiciatis expedita!
          Libero impedit voluptas tenetur quo quasi harum accusantium esse blanditiis ratione assumenda eveniet, officiis corporis magnam debitis saepe modi aliquam quidem odio cupiditate aperiam distinctio doloremque? Dolor doloribus rerum rem!
          Recusandae quis maiores ducimus et quae excepturi tempora maxime provident assumenda! Aspernatur reprehenderit incidunt maxime amet voluptas doloremque excepturi eum magni quasi, quis cumque sequi unde sapiente ducimus, suscipit non!
          Doloremque laboriosam aspernatur in corporis magni repellat ut quos quae quisquam saepe dolorum, pariatur ex asperiores, aut quo officiis. Atque, accusamus. Qui, nihil. Nobis ipsam porro id impedit possimus sit?
          Harum suscipit animi quisquam ratione modi omnis ipsa perspiciatis a ipsam officia. Magni ipsum, aspernatur dolorum pariatur amet labore sit. Iusto accusantium, modi fugit ex voluptate totam sint quisquam et?
          Quasi eos accusamus corrupti fugit voluptates velit nulla exercitationem quis quia consequuntur vero, voluptas expedita in, neque minima placeat mollitia eveniet dolorum sunt quaerat. Itaque quisquam atque ad rerum ut.
          Repellat, maxime officiis similique placeat consequatur veritatis natus culpa nihil soluta quae. Alias ipsum ea suscipit consequatur optio dolore nam fugit doloremque accusantium quo, magni aliquam, impedit aliquid recusandae at!
          Perspiciatis magnam laboriosam neque nostrum consequatur quia consectetur itaque ducimus accusantium facilis dolorem, quidem cumque soluta assumenda iste doloribus saepe fugiat perferendis quo. Iusto, est. Ut eos amet numquam blanditiis.
          Nulla itaque nam nihil labore molestiae ipsa vero ad commodi. Veniam aspernatur iure, corporis excepturi nobis rem dolorem accusantium in ipsa quam, placeat reiciendis? Reprehenderit fuga autem recusandae nulla consequatur?
          Nam labore, totam saepe atque similique repellat unde praesentium culpa impedit blanditiis ipsam magni. Aperiam dolor eligendi quasi at rem nisi ipsum repellendus, soluta quas aspernatur sit provident tempore voluptates.
          Ea repudiandae deleniti velit quibusdam quam rem, saepe similique voluptas recusandae quae aspernatur ducimus esse facilis nihil corporis? Esse id fugit labore sapiente tempore, aut ratione excepturi unde error delectus!
          Rem excepturi minima, sunt iste totam quia ipsam odit ab consequatur pariatur eius tempore, deleniti, quos in? Beatae suscipit a architecto quidem, doloremque eligendi! Ducimus corporis beatae illum eos nesciunt?
          Quia alias neque suscipit labore? Quaerat exercitationem suscipit impedit accusamus, harum quibusdam voluptatum cupiditate architecto excepturi possimus autem et minima fugiat nostrum saepe quisquam consequatur ipsa sapiente odit dolorum in.
          Omnis magni architecto eligendi at ut est quod suscipit itaque officia molestiae corrupti inventore sapiente, debitis iure iusto necessitatibus adipisci blanditiis ex cum laboriosam ducimus pariatur? Ab quas eos dolore.
          Debitis, ad! Recusandae suscipit officiis nobis tenetur quae voluptatibus unde adipisci corporis ratione, nisi rem expedita reprehenderit atque? Est dicta quo, saepe sequi quibusdam illo corrupti vel mollitia excepturi odio.
          Maiores, quia beatae eaque voluptate exercitationem officia. Voluptate, consequuntur, vel iste amet officia aperiam dolor numquam, quae minus nam sed rem! Unde nemo facilis, illum aspernatur tenetur aliquid eos optio?
          Quod ratione animi temporibus culpa dicta rem incidunt quae ipsum veniam? Rerum doloremque, enim, culpa totam aperiam blanditiis in quia dolorum minus possimus esse ab, animi perferendis. Neque, consequatur officia!
          Ducimus nobis saepe animi atque explicabo ab unde aliquam? Culpa obcaecati harum veritatis odio maiores, dolores, pariatur quam provident quod tempora nam earum, possimus placeat alias similique optio voluptatum perferendis?
          Sapiente reprehenderit est ut vitae rem dolorem quod fugiat quam, repudiandae, dignissimos optio quibusdam expedita, cupiditate molestias deleniti eos nesciunt id? Cumque, saepe. Iure delectus commodi earum quia. Laudantium, molestias?
          Doloremque laborum consequuntur eveniet culpa incidunt, hic explicabo accusantium ut est nisi pariatur blanditiis eaque. Sed saepe doloribus sit ullam non esse enim vel minima similique magnam labore, dolores illo!
          Ut, est ipsam deserunt eum eos nemo suscipit animi repellat, voluptas ipsa delectus dolor exercitationem sint, nostrum harum similique perferendis magnam ratione omnis! Modi, sed! Fuga obcaecati voluptates architecto ad.
          Pariatur assumenda dignissimos, repudiandae asperiores quod repellendus ipsam ipsa, amet nisi consectetur perferendis, praesentium natus dolorum dolore. Asperiores, enim, quos, non aspernatur error reiciendis rerum ducimus magnam molestiae quod sit.
        </p>
    </div>
  )
}

export default Settings